---
language: node_js
node_js:
<<<<<<< HEAD
  - "6"

sudo: required
=======
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

dist: trusty

addons:
  chrome: stable
>>>>>>> 78e6df8... v3.3.0...v3.17.0

cache:
  directories:
    - $HOME/.npm

dist: trusty

env:
<<<<<<< HEAD
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.18.2
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-default

matrix:
=======
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
>>>>>>> 78e6df8... v3.3.0...v3.17.0
  fast_finish: true

<<<<<<< HEAD
before_install:
  - npm config set spin false
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install


script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm test
  - npm run coverage

addons:
  chrome: stable

after_success:
  - npm run coveralls
=======
  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint
        - npm run test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm run test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
>>>>>>> 78e6df8... v3.3.0...v3.17.0
